---
 - name: Launching aws ec2 instance
   hosts: localhost
   gather_facts: false
   tasks:
   - name: Launching ec2 instance with ec2 module 
     ec2:
      instance_type: t2.micro
      image: your ami id
      key_name: your key
      region: us-east-1
